version: "3.8"
services:
  postgres:
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    image: postgres:latest
    volumes:
      - /var/tiny-template-postgres:/var/lib/postgresql/data
    ports:
      - "5454:5432"